### ISSUE TITLE
Bug report test cases 22

### ISSUE THREAD

**Issue by MaximeTAlgosup** [algosup/2023-2024-project-3-virtual-processor-team-4#45]
# Tested Version 
v0.0

## Description
The code run even when too many arguments in the bi instructions.

## Steps
Compile and run assembler.exe.
Create a file named example.asm containing:
```
bi label ra
label:
```
cmdline: assembler.exe example.asm example.bin.

## Context
Doing the test cases before accepting the pull request: "Merge of preprocessor as of 02/21".

## Actual Result (optional screenshot)
<img width="818" alt="Screenshot 2024-02-22 173647" src="https://github.com/algosup/2023-2024-project-3-virtual-processor-team-4/assets/145995586/4dfae215-f340-49b5-bc9e-3f7e42a2c1d0">

## Security Criteria
3

## Discovery/Resolve Date
02/22/2024

## Expected Result
bi, calli and jmp only use an imm/address and no more parameters.

## Possible Solution
//
## Other
//

**Comment by maxbernard3** [comment]
Resolved on the side of the assembler by catching when there are too many argument on some specific type J operation

**Comment by MaximeTAlgosup** [comment]
<img width="243" alt="Screenshot 2024-02-22 182030" src="https://github.com/algosup/2023-2024-project-3-virtual-processor-team-4/assets/145995586/736164ad-601e-486f-8ea0-df063e820a12">
I think there is still a problem Max.

**Comment by maxbernard3** [comment]
sorry I had forgoten to change the boolean I use to record error in the function.

changed 
```c
if(notTwoArg && instruction.param1_t != NULL_){
            printf("Error: too many argument in line %d\n", instruction.lineNumber);
}
```
to
```c
if(notTwoArg && instruction.param1_t != NULL_){
            error = true;
            printf("Error: too many argument in line %d\n", instruction.lineNumber);
}
```
